### ISSUE TITLE
add a parser for no nodes

### ISSUE THREAD

**Issue by olafklinke** [nikita-volkov/xml-parser#1]
`XmlParser.AstParser.Node` has no way of catching a NodeError, which would be one way of creating a parser for empty strings. Suppose you have a parser `p :: Content a` which accepts the empty string. The library should make `AstParser.contentNode p` succeed on an element with no children, but currently throws `NotAvailableNodeError`. 
Alternatively, AstParser should provide a top-level function of type  `a -> Nodes a` which returns the given element precisely when `XmlParser.NodeConsumerState.fetchNode` returns `Nothing`. For such a function to be useful, the `Element` and `Node` monads should have a binary operator for alternatives. (An `Alternative` instance is impossible due to a lack of reasonable `empty` value.)

**Comment by nikita-volkov** [comment]
Fix is released in 0.1.1

**Comment by nikita-volkov** [comment]
Thanks for the detailed report! :)
